### ISSUE TITLE
Additions for the build script

### ISSUE THREAD

**Issue by bonelifer** [hanzala123/world-clock-xfce-plugin#1]
Found your post on Reddit, really nice plugin. For Ubuntu these first three are not going to be part of a typical users default install. I'd also include installing meson and ninja as they aren't likely installed by default either. They weren't on my install and I'm not a typical user.  The last two lines below them get the version of python and use sed to replace what you have in plugin.c with the correct default version for their install.

So add Ubuntu Section in git readme:
sudo apt-get libxfce4panel-2.0
sudo apt-get install python-gi-dev
sudo apt-get install libgtk-3-dev
sudo apt-get install meson ninja

Add this to your install.sh script:
```
version=`python3 -c "import sys;t='{v[0]}.{v[1]}'.format(v=list(sys.version_info[:2]));sys.stdout.write(t)";`
```
```
sed -i "s/libpython3.10.so/libpython$version.so/g" ./src/plugin.c
```

**Comment by hanzala123** [comment]
@bonelifer Thanks for pointing this out. I have made the necessary changes. I am closing this issue. Let me know if you have any  new suggestions :).
