### ISSUE TITLE
If you have more than three timezones...

### ISSUE THREAD

**Issue by bonelifer** [hanzala123/world-clock-xfce-plugin#2]
If you have more than three timezones, they get squished together
![worldtime](https://user-images.githubusercontent.com/121736/170847976-74d8997a-d0fc-4867-b860-35d06efc017b.jpg)
.

**Comment by bonelifer** [comment]
Also add second dateformat for the entries(ie in the picture Germany and England).

**Comment by hanzala123** [comment]
This has been fixed in the latest release. Thank you for pointing it out.
